### ISSUE TITLE
Machine Model Bar Plugin uses expensive calls

### ISSUE THREAD

**Issue by grahamgilbert** [salopensource/sal#112]
Retrieving the whole machine model can take a long time - for large installs, the plugin never loads. We should just retrieve the values we need. As @sheagcraig has turned the python up to 11 on this one (I'd never even heard of `Counter`), this may take me a while.

@sheagcraig do you know how this works enough so that we can use `.values()` to only get the info we need rather than the whole model?

**Comment by grahamgilbert** [comment]
I think I got this in the `fixup_machinemodelsbar` branch - can you review @sheagcraig ?

**Comment by sheagcraig** [comment]
Superficially, that looks correct to me.

I guess the TODO points out the need to not have to compute this over and over again too. We want Sal to get new model names as they come out, but the list probably doesn't change existing entries very often. It's also not good to just include the model list as data, because then you have to keep it up to date. But it could definitely just be stored in the database the first time any particular value is encountered. I don't have the bandwidth to implement that at the moment, unfortunately.
