### ISSUE TITLE
Installed Paths for Application Inventory links do not work

### ISSUE THREAD

**Issue by gregneagle** [salopensource/sal#135]
When looking at the detail for an application in the Application Inventory, clicking on the number badge buttons next to any listed installed path results in a "400 Bad Request" error from the server.

URLs are of the form:
`https://sal.myorg.com/inventory/list/all/0/1822/path//Applications/HandBrake.app/`

The problem appears to be the double slash after "path". Removing one of those slashes bypasses the "400 Bad Request" error, but then no results are found:

"All machines where HandBrake path is Applications/HandBrake.app" -- "No data available in table"

**Comment by grahamgilbert** [comment]
Ping @sheagcraig

**Comment by sheagcraig** [comment]
I'll take a look!

**Comment by sheagcraig** [comment]
So this is because the paths all include slashes. The first slash gets tacked onto the URL, resulting in a double. This actually works just fine on my server, which is why I must have missed this.

Annoyingly, as I'm going around in circles trying to figure out the best way to fix this, I'm having a hard time quoting the path value as part of the `{% url %}` django tag call to reverse the URL. The dirty solution is to just construct the URL manually by concatenating things together. I'm sure there's a better way to solve this. Let me research further.

**Comment by sheagcraig** [comment]
@gregneagle, please let me know if that solves your issue or not. I can't make it not work on my setup (I can of course see the double-slashes in the URL).

**Comment by gregneagle** [comment]
...and it's going to take me a bit longer to test. I set up a test environment using the build-in Django development server and of course it doesn't have any issues with the original application paths.

So it's going to take me a little bit to set up a test environment that replicates more of my production environment.

I'm working on getting the Munki 3.1 release out the door this week, so I might not get the testing done today.

**Comment by sheagcraig** [comment]
So a year later, how's it looking @gregneagle?

**Comment by gregneagle** [comment]
Sadly, I don't know.

**Comment by sheagcraig** [comment]
Want to keep it open? (@gregneagle)

**Comment by gregneagle** [comment]
Let's close it. If no-one else has reported this issue in the past year it's either fixed or unique to my configuration.
