### ISSUE TITLE
Application Inventory Search Permissions Issue

### ISSUE THREAD

**Issue by Zolotkey** [salopensource/sal#169]
The Issue Short Version:

Application Inventory Search Returns 403 to Non-Global Admin's with Business Unit Granted Access.

Long Version:

Users are not able to view Application Inventory when logged in as Read Only or Read/Write Privileges for sal and also has access to Business Unit.  Here are some specs:

Sal Version: 3.2.7.1013
Apache Version: 2.4.29
Apache24 HTTPS Proxy to Sal 8000 with static alias
Django LDAP Config
FreeBSD 11.1 with Sal source install (git tag update)
Apache24 Log: http://imperialba.se/sal/error.log

@sheagcraig

**Comment by sheagcraig** [comment]
Hi @Zolotkey!

So, I've got bad news for you... I can't replicate your issue.

I logged into our production server so that I would have lots of data to toy around with, and I ran the code all manually. I'll add that in so you can try it and paste in your results. Maybe that will help us see where things are going wrong.

Full disclosure: I'm using a custom Docker image that adds LDAP authentication, although I don't believe that should make a difference. If we get stymied, I'll set up a fresh Sal and confirm that regular-old-Django-auth fails too.

So bear with me if this is too much information. I'll just assume it's all new to you, so forgive me if it isn't.

I am running as a container, so I use the Django shell by first doing
`docker exec -it sal bash`
This conveniently drops me right into the Sal directory. I can then run `./manage.py shell` to get into a (somewhat) functional python shell.

If you're not running with Docker, you'll probably have to activate a virtualenv prior to running the above.

I created a testing user (read only) named "frroose", which would be our standard shortname convention for Franklin Delano Roosevelt... Despite having `ADD_TO_ALL_BUSINESS_UNITS` set to True, I discovered he has no BU permissions. This is actually helpful, as we can test that the access decorator rejects him when expected first:
```
>>> from server.models import User, BusinessUnit
>>> fdr = User.objects.get(username='frroose')
>>> fdr.businessunit_set.all()
<QuerySet []>
>>> from sal.decorators import has_access
>>> from sal.decorators import is_global_admin
>>> is_global_admin(fdr)
False
>>> apac = BusinessUnit.objects.get(name='APAC')
>>> has_access(fdr, apac)
False
>>> fdr.businessunit_set.all()
<QuerySet [<BusinessUnit: APAC>]>
>>> has_access(fdr, apac)
True
```

Okay, as expected. I then went into the GUI and added FDR to the APAC business unit.
```
>>> fdr.businessunit_set.all()
<QuerySet [<BusinessUnit: APAC>]>
>>> has_access(fdr, apac)
True
```

Now, technically, `has_access` and `is_global_admin` are just helper functions. So I guess it's possible that there's something funny going on in the actual decorator code that calls them (`sal/decorators.py:L26-56`)

Why don't we start with taking a look at one of your users who is having issues and let's just confirm the `has_access` function is working as expected. It would look like the above, just substituting in the username and business unit name where appropriate.

**Comment by sheagcraig** [comment]
Interesting. So that part is working correctly.

Does the same user have problems seeing a machine group inventory page from that business unit? And what about a machine inventory page from that business unit?

Do you have a testing server with this issue that you can fool around on? We can't be dropping into the debugger on your "real" server.

**Comment by sheagcraig** [comment]
I guess another question is, can this same user get to other views in the inventory app?

E.g. the ApplicationListView and ApplicationDetailView? (urls from `application/<group_type>/<group_id>/<pk>` or just `inventory/<group_type>/<group_id>/`.

**Comment by Zolotkey** [comment]
Unfortunately all of inventory is 403 for the test user, no matter the BU or Machine Group.

https://sal/inventory/machine_group/2/ gets 403
https://sal/inventory/application/all/0/2031/ gets 403
https://sal/inventory/machine/7/ gets 403

Test server is up and running.

**Comment by epackorigan** [comment]
I have the same problem as Zolotkey. the output is similar.
I believe neither of us is using Docker.
