### ISSUE TITLE
Device Application Inventory `FieldError`

### ISSUE THREAD

**Issue by sheagcraig** [salopensource/sal#373]
The original issue is solved, but I'm now getting the same error (in my browser) one step deeper into the app. I can select a single client, click on "Application Inventory" and when I then try to find  info about a (any) application on that client I get the same browser error.
I'll try to capture the logs for it as well.

_Originally posted by @jby in https://github.com/salopensource/sal/issues/369#issuecomment-594391151_

**Comment by sheagcraig** [comment]
https://github.com/salopensource/sal/issues/369#issuecomment-594403633

**Comment by jby** [comment]
@sheagcraig - let me know if you want anything tested...

**Comment by sheagcraig** [comment]
@jby please by all means. This was pretty clear once I dug around; it's a pretty odd problem to have. But having some verification from others always helps.

We can probably cut a release (and one of sal-scripts) once you test things out and give them the 👍

**Comment by jby** [comment]
Sorry, I've been out of the office with a bad head cold for more than a week now.
I haven't been able to test this because of that.
I'll probably work tomorrow (Thursday) and will test this then.

**Comment by jby** [comment]
Since I had no idea on how to pull your fix into my docker container (macadmins/sal) I simply downloaded inventory/views.py onto my server and made sure I could reach it from within the container then simply overwrote the existing views.py with the downloaded one from here.

I'd say that the issue is fixed after trying this...
