### ISSUE TITLE
facter3 results in 502 on checkin

### ISSUE THREAD

**Issue by arubdesu** [salopensource/sal#38]
As soon as the .7.5 version of sal-scripts is told to use facter3, even though I get some data for that part of the report, it's only 13 of the 38 keys in that data. I can't see anything wrong between https://github.com/salopensource/sal/blob/master/server/views.py#L1511 and https://github.com/salopensource/sal/blob/master/server/models.py#L237, since facter2 was sending the same sorts of data types, so I can't find where the issue is happening while I'm not running with DEBUG on. The current result is a 502 on the checkin section, but at least the catalogs submission in the same run go through. If it helps for correlation, the keys in that dict that are missing in Sal(including some custom facts we use and PE-specific ones) are:
```
 'aio_agent_build'
 'custom_auth_conf'
 'dmi'
 'facterversion'
 'filesystems'
 'identity'
 'is_virtual'
 'kernelmajversion'
 'kernelversion'
 'mac_admin_users'
 'memory'
 'mountpoints'
 'munki_catalog'
 'munki_included_manifest'
 'mysql_server_id'
 'os'
 'path'
 'pe_concat_basedir'
 'processors'
 'puppet_files_dir_present'
 'ruby'
 'ssh'
 'staging_http_get'
 'system_profiler'
 'system_uptime'
```

**Comment by grahamgilbert** [comment]
So this is due to the structured facts. Currently they're stored as a flat table with just fact name and fact data fields. The question is, do we try to replicate this (hard, but not impossible), or do we flatten the structure? There is ``--show-legacy`` which will get all the 'old' facts out, but this is a sticking plaster so we might as well fix it now.

With flattening, I was thinking something like:
```
$ sudo /opt/puppetlabs/bin/facter --puppet --yaml system_uptime
system_uptime:
  days: 0
  hours: 0
  seconds: 1242
  uptime: 0:20 hours
```

Would be stored as:

```
system_uptime->days = 0
system_uptime->hours = 0
system_uptime->seconds = 1242
system_uptime->uptime = 0:20 hours
```

That delimiter was chosen arbitrarily, but it needs to be something odd enough to not likely be in a fact name. Flattening would make it easier to be backwards compatible with 3.8, since we can use the same table and just handle this in python. If we do something else, we'd need to re-wire the tables (which also makes all the existing plugins that use that info out of date).

**Comment by arubdesu** [comment]
It was odd to learn I couldn't classify based on structured facts in the PE console, so all I have in the way of custom facts right now are flat, anyway. Especially with the rise/integration of osquery I don't think it's worth reinventing the wheel over, table-wise.
As for a delimiter, how about the hash rocket?

**Comment by grahamgilbert** [comment]
This is fixed in the client side scripts
