### ISSUE TITLE
Today Widget includes other machines as well.

### ISSUE THREAD

**Issue by weswhet** [salopensource/sal#383]
**Describe the bug**
When viewing the Today Widget on the main dashboard, which goes to `/list/Activity/today/all/0/` the list includes machines that were seen more than a day ago.

**To Reproduce**
1. Go to main dashboard page
2. Click on the Blue Today Widget
3. Scroll down through the list of machines. 
4. See machines that checked in more than 

**Expected behavior**
My assumption is that only machines that have checked in within the last 24 hours or on today's date only would be on this list. 
**Server (please complete the following information):**
 - Version 4.1.2.2119

**Comment by weswhet** [comment]
![Screen Shot 2020-04-22 at 3 06 22 PM](https://user-images.githubusercontent.com/6865785/80039351-7aefd200-84ac-11ea-82b0-a983e26c0420.png)

**Comment by sheagcraig** [comment]
This is the result of several of the plugins using global variables that are the results of `datetime.datetime.now` or some delta of it. When the plugins got loaded 2+ times for each actual use, this was calculated at the time of use. However, since the plugin manager singleton keeps imported references to all of the plugins now, these don't get recalculated repeatedly.

This will just be a matter of hunting down all the places where dates are set globally and moving them into the actual plugin funcs.
