### ISSUE TITLE
Puppet Status widget doesn't work

### ISSUE THREAD

**Issue by grahamgilbert** [salopensource/sal#403]
**Describe the bug**
After updating to 4.x, I noticed that the puppet status widget no longer reports... Well, anything.

**Comment by octomike** [comment]
I've looked into this a little today and it seems to me that this is just broken since the Machine model does not contain the relevant data anymore. Sal and the puppetstats plugin expect:

```python
def _puppet_facts(machine):
    info_names = ('puppet_version', 'puppet_errors', 'last_puppet_run')
    rows = _get_management_facts(machine, 'Puppet', info_names)
    return rows
```

These facts are not standard puppet and there are two places where we could re-introduce them.

1. in [puppet_checkin_module](https://github.com/salopensource/puppet_checkin_module/blob/master/payload/usr/local/sal/checkin_modules/puppet_checkin_module.py#L40)

2. in a custom post checkin processor [somewhere here](https://github.com/salopensource/sal/blob/main/server/non_ui_views.py#L377)

I tested both approaches and they work fine, however I favor a server side change (2.). There is one little caveat though. Right now the puppet checkin module only sends managed items (resources) and not additional metadata from the report. We would need more metadata to include the report timestamp to create the precise `last_puppet_run` fact. Instead we could just take a timestamp from any of the managed items and use that. It's only a (good) estimation for the puppet run, but technically not the correct value.

The `puppet_version` fact could just be renamed to `puppetversion` (this is a standard fact I think) and `puppet_errors` can just be counted from the managed items hash passed by the checkin module.

If you like I can create a PR for both approaches. Let me know, what you think.

**Comment by grahamgilbert** [comment]
I think sending the correct info from the checkin module is the right approach rather than guessing. Puppet facts aren't really anything special, so probably shouldn't get any special processing on the server end.

**Comment by octomike** [comment]
Okay, can do. One question though. `fact_data` is a Textfield and would contain the (ruby version) of the ISO8601 time format as a string.
[puppetsts.py](https://github.com/salopensource/sal/blob/cee85c48172f5d1f6983099fbf973892f97c62c6/server/plugins/puppetstatus/puppetstatus.py#L63) is currently filtering for 

```python
  ... filter(facts__fact_data__lte=today - timedelta(days=30))
```

Is the `lte` filter smart enough to parse `fact_data` into a datetime object automatically?

**Comment by octomike** [comment]
Nevermind, we can `annotate(last_run=Cast(..))` to parse the string data on the fly in the QuerySet. I will test more and open two minimal PRs later.
